import PDFDocument from 'pdfkit';

// ─── Inquiry PDF ─────────────────────────────────────────────────────────────

export interface InquiryDocumentData {
    referenceNumber: string;
    clientName: string;
    clientEmail: string;
    clientPhone?: string;
    serviceRequired: string;
    timelinePreference?: string;
    projectDescription?: string;
    internalComments?: string;
    consultantName?: string;
    consultantEmail?: string;
    status: string;
    createdAt: string;
}

const renderInquiryPage = (doc: any, data: InquiryDocumentData) => {
    // Header
    doc.fillColor('#333333').font('Helvetica-Bold').fontSize(20).text('GASCART - Professional Consultation Inquiry', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).fillColor('#666666').text(`Reference: ${data.referenceNumber}`, { align: 'right' });
    doc.text(`Date: ${new Date(data.createdAt).toLocaleDateString()}`, { align: 'right' });
    doc.moveDown();

    // Consultation Info
    doc.fontSize(14).fillColor('#1a1a2e').text('Service Details', { underline: true });
    doc.fontSize(12).fillColor('#333333').text(`Service Required: ${data.serviceRequired}`);
    if (data.timelinePreference) doc.fontSize(12).text(`Timeline: ${data.timelinePreference}`);
    doc.moveDown();

    // Client Info
    doc.fontSize(14).fillColor('#1a1a2e').text('Client Information', { underline: true });
    doc.fontSize(12).fillColor('#333333').text(`Name: ${data.clientName}`);
    doc.text(`Email: ${data.clientEmail}`);
    if (data.clientPhone) doc.text(`Phone: ${data.clientPhone}`);
    doc.moveDown();

    // Expert Info
    doc.fontSize(14).fillColor('#1a1a2e').text('Assigned Expert', { underline: true });
    if (data.consultantName) {
        doc.fontSize(12).fillColor('#333333').text(`Expert: ${data.consultantName}`);
        doc.text(`Email: ${data.consultantEmail || 'N/A'}`);
    } else {
        doc.fontSize(12).fillColor('#e67e22').text('Status: Unassigned (Admin to Assign)');
    }
    doc.moveDown();

    // Project Details
    if (data.projectDescription) {
        doc.fontSize(14).fillColor('#1a1a2e').text('Project Brief', { underline: true });
        doc.fontSize(10).fillColor('#444444').text(data.projectDescription, { align: 'justify' });
        doc.moveDown();
    }

    // Internal Notes
    if (data.internalComments) {
        doc.fontSize(14).fillColor('#2c3e50').text('Internal Admin Notes (Confidential)', { underline: true });
        doc.fontSize(10).fillColor('#444444').text(data.internalComments, { align: 'justify' });
        doc.moveDown();
    }

    // Footer
    const bottom = doc.page.height - 80;
    doc.fontSize(8).fillColor('#999999').text(
        'This is a formal consultation inquiry request generated by GASCART. Confidentiality of client information and project briefs is maintained under standard platform privacy terms.',
        50,
        bottom,
        { align: 'center', width: 500 }
    );
};

export const generateInquiryPDF = async (data: InquiryDocumentData): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        renderInquiryPage(doc, data);
        doc.end();
    });
};

export const generateBulkInquiryPDF = async (items: InquiryDocumentData[]): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        items.forEach((data, index) => {
            if (index > 0) doc.addPage();
            renderInquiryPage(doc, data);
        });

        doc.end();
    });
};


// ─── RFQ PDF ─────────────────────────────────────────────────────────────────

export interface RFQDocumentData {
    rfqId: string;
    productName: string;
    submittedFields: Record<string, any>;
    userEmail: string;
    full_name?: string;
    company_name?: string;
    createdAt: string;
}

const renderRFQPage = (doc: any, data: RFQDocumentData) => {
    // Header
    doc.fillColor('#333333').font('Helvetica-Bold').fontSize(20).text('GASCART - Technical Enquiry', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).fillColor('#666666').text(`Enquiry ID: ${data.rfqId}`, { align: 'right' });
    doc.text(`Date: ${new Date(data.createdAt).toLocaleDateString()}`, { align: 'right' });
    doc.moveDown();

    // Product Info
    doc.fontSize(14).fillColor('#1a1a2e').text('Industrial Asset Details', { underline: true });
    doc.fontSize(12).fillColor('#333333').text(`Asset Name: ${data.productName}`);
    doc.moveDown();

    // Customer Info
    doc.fontSize(14).fillColor('#1a1a2e').text('Client Information', { underline: true });
    doc.fontSize(12).fillColor('#333333').text(`Email: ${data.userEmail}`);
    if (data.full_name) doc.fontSize(12).text(`Name: ${data.full_name}`);
    if (data.company_name) doc.fontSize(12).text(`Company: ${data.company_name}`);
    doc.moveDown();

    // Technical Specifications
    doc.fontSize(14).fillColor('#1a1a2e').text('Technical Requirements', { underline: true });
    doc.moveDown(0.5);

    Object.entries(data.submittedFields).forEach(([label, value]) => {
        // Skip metadata fields if they exist
        if (['enquiry_id', 'company_name', 'item_quantity', 'item_price'].includes(label)) return;
        
        doc.fontSize(10).font('Helvetica-Bold').fillColor('#333333').text(`${label}: `, { continued: true });
        doc.font('Helvetica').fillColor('#444444').text(`${value}`);
        doc.moveDown(0.5);
    });

    // Footer
    const bottom = doc.page.height - 80;
    doc.fontSize(8).fillColor('#999999').text(
        'This is a system-generated technical requisition document. Confidentiality of engineering parameters is maintained under standard GASCART NDA terms.',
        50,
        bottom,
        { align: 'center', width: 500 }
    );
};

export const generateRFQPDF = async (data: RFQDocumentData): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        renderRFQPage(doc, data);
        doc.end();
    });
};

export const generateBulkRFQPDF = async (items: RFQDocumentData[]): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        items.forEach((data, index) => {
            if (index > 0) doc.addPage();
            renderRFQPage(doc, data);
        });

        doc.end();
    });
};

// ─── Invoice PDF ──────────────────────────────────────────────────────────────

export interface InvoiceOrderItem {
    quantity: number;
    price_at_purchase: number;
    product?: { name?: string };
}

export interface InvoiceShippingAddress {
    full_name?: string;
    address_line1?: string;
    city?: string;
    state?: string;
    postal_code?: string;
    zip_code?: string;
    phone?: string;
}

export interface InvoiceData {
    orderId: string;
    createdAt: string;
    paymentStatus: string;
    razorpayPaymentId?: string;
    totalAmount: number;
    paidAmount?: number;
    balanceDue?: number;
    orderItems: InvoiceOrderItem[];
    shippingAddress: InvoiceShippingAddress;
    profile?: { full_name?: string; email?: string };
}

export const generateInvoicePDF = (data: InvoiceData): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        const shortId = data.orderId.slice(-8).toUpperCase();

        // ── Brand & Header ────────────────────────────────────────────────────
        doc.fillColor('#444444').font('Helvetica-Bold').fontSize(22).text('GASCART', 50, 50);
        doc.font('Helvetica').fontSize(10).text('Industrial Ecommerce Solutions', 50, 78);
        doc.text('123 Industrial Ave, Tech City, 560001', 50, 93);
        doc.text('support@gascart.com | +91 234 567 890', 50, 108);

        doc.font('Helvetica-Bold').fontSize(22).text('INVOICE', 200, 50, { align: 'right' });
        doc.font('Helvetica').fontSize(10).fillColor('#444444');
        doc.text(`Invoice #: INV-${shortId}`, 200, 78, { align: 'right' });
        doc.text(`Date: ${new Date(data.createdAt).toLocaleDateString()}`, 200, 93, { align: 'right' });
        doc.text(`Status: ${data.paymentStatus.toUpperCase()}`, 200, 108, { align: 'right' });

        if (data.razorpayPaymentId) {
            doc.text(`Payment ID: ${data.razorpayPaymentId}`, 200, 123, { align: 'right' });
        }

        doc.moveTo(50, 150).lineTo(550, 150).strokeColor('#eeeeee').stroke();

        // ── Customer / Shipping Info ──────────────────────────────────────────
        const customerInfoTop = 180;
        doc.fontSize(12).font('Helvetica-Bold').fillColor('#333333').text('Bill To:', 50, customerInfoTop);
        doc.fontSize(10).font('Helvetica').fillColor('#444444');
        doc.text(data.profile?.full_name || 'Customer', 50, customerInfoTop + 25);
        doc.text(data.profile?.email || '', 50, customerInfoTop + 40);
        doc.text(data.shippingAddress.phone || '', 50, customerInfoTop + 55);

        doc.fontSize(12).font('Helvetica-Bold').fillColor('#333333').text('Ship To:', 300, customerInfoTop);
        doc.fontSize(10).font('Helvetica').fillColor('#444444');
        doc.text(data.shippingAddress.full_name || 'Customer', 300, customerInfoTop + 25);
        
        // Use a wrapping text block for address line 1 to avoid overlap if it's long
        doc.text(data.shippingAddress.address_line1 || '', 300, customerInfoTop + 40, { width: 250 });
        
        // City, State, Zip - Pushed down further to accommodate potential wrapping above
        doc.text(
            `${data.shippingAddress.city || ''}, ${data.shippingAddress.state || ''} ${data.shippingAddress.postal_code || data.shippingAddress.zip_code || ''}`,
            300,
            customerInfoTop + 75
        );

        doc.moveTo(50, 280).lineTo(550, 280).strokeColor('#eeeeee').stroke();

        // ── Items Table ───────────────────────────────────────────────────────
        const tableTop = 300;
        doc.fontSize(10).font('Helvetica-Bold').fillColor('#333333').text('Item Description', 50, tableTop);
        doc.text('Qty', 300, tableTop);
        doc.text('Unit Price', 380, tableTop);
        doc.text('Total', 480, tableTop);
        doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).strokeColor('#cccccc').stroke();

        let y = tableTop + 30;
        doc.font('Helvetica');
        data.orderItems.forEach((item) => {
            const name = item.product?.name || 'Product';
            doc.fontSize(10).fillColor('#444444').text(name, 50, y, { width: 240 });
            doc.text(item.quantity.toString(), 300, y);
            doc.text(`Rs.${item.price_at_purchase.toFixed(2)}`, 380, y);
            doc.text(`Rs.${(item.quantity * item.price_at_purchase).toFixed(2)}`, 480, y);
            y += 20;
            doc.moveTo(50, y - 5).lineTo(550, y - 5).strokeColor('#f9f9f9').stroke();
        });

        // ── Summary ───────────────────────────────────────────────────────────
        y += 20;
        const summaryX = 350;

        doc.fontSize(10).font('Helvetica').fillColor('#333333').text('Subtotal:', summaryX, y);
        doc.text(`Rs.${data.totalAmount.toFixed(2)}`, 480, y, { align: 'right' });

        if (data.paidAmount && data.paidAmount > 0) {
            y += 20;
            doc.text('Paid Amount:', summaryX, y);
            doc.text(`Rs.${data.paidAmount.toFixed(2)}`, 480, y, { align: 'right' });
        }

        if (data.balanceDue && data.balanceDue > 0) {
            y += 20;
            doc.font('Helvetica-Bold').fillColor('#e74c3c').text('Balance Due:', summaryX, y);
            doc.fillColor('#e74c3c').text(`Rs.${data.balanceDue.toFixed(2)}`, 480, y, { align: 'right' });
        }

        y += 25;
        doc.fontSize(12).font('Helvetica-Bold').fillColor('#333333').text('Total Amount:', summaryX, y);
        doc.fontSize(12).fillColor('#2ecc71').text(`Rs.${data.totalAmount.toFixed(2)}`, 480, y, { align: 'right' });

        // ── Footer ────────────────────────────────────────────────────────────
        const footerTop = 680;
        doc.moveTo(50, footerTop).lineTo(550, footerTop).strokeColor('#eeeeee').stroke();
        doc.fontSize(10).font('Helvetica').fillColor('#888888').text(
            'Thank you for choosing GASCART for your industrial needs.',
            50, footerTop + 20,
            { align: 'center', width: 500 }
        );
        doc.text(
            'Terms & Conditions apply (See Page 2). This is an electronically generated invoice.',
            50, footerTop + 35,
            { align: 'center', width: 500 }
        );

        // ── Second Page: Terms & Conditions ──────────────────────────────────
        doc.addPage();
        
        doc.fillColor('#333333').font('Helvetica-Bold').fontSize(16).text('TERMS AND CONDITIONS', 50, 50, { align: 'center' });
        doc.moveTo(50, 75).lineTo(550, 75).strokeColor('#eeeeee').stroke();
        
        let termsY = 95;
        const termsFontSize = 8;
        const headerFontSize = 10;
        
        const terms = [
            {
                title: '1. Acceptance of Terms',
                content: 'By accessing GasCart (www.gascart.in), using our services, or making a purchase, you agree to be bound by these Terms of Service. Creation of a user account or login shall constitute full acceptance.'
            },
            {
                title: '2. Nature of the Platform',
                content: 'GasCart, operated by Stut Instruments, is a B2B marketplace and sourcing facilitator for the Bio-CNG and CBG ecosystem. GasCart acts as an intermediary and is not the manufacturer or direct seller unless explicitly stated.'
            },
            {
                title: '3. Buyer Responsibilities',
                content: 'Buyers are responsible for independent technical and commercial evaluation, verifying specifications, reviewing vendor credentials, and negotiating terms directly with vendors.'
            },
            {
                title: '4. No Commercial Liability',
                content: 'GasCart is not liable for product defects, delivery delays, performance failures, or contractual disputes between buyers and vendors. Liability is limited to the facilitation fee earned by GasCart on the specific transaction.'
            },
            {
                title: '5. Payments and Transactions',
                content: 'Terms for payment, delivery, and warranty are governed by the respective vendor/OEM agreements. GasCart is not a party to the commercial contract between buyer and seller.'
            },
            {
                title: '6. Intellectual Property',
                content: 'All content and branding are owned by Stut Instruments. Users may not reproduce, copy, or exploit platform content without written permission.'
            },
            {
                title: '7. Data & Privacy',
                content: 'Use of the platform is governed by our Privacy Policy. Users consent to data sharing necessary for RFQ processing and vendor engagement.'
            },
            {
                title: '8. Governing Law',
                content: 'These terms are governed by the laws of India. Any disputes are subject to the exclusive jurisdiction of courts in Sirsi, Karnataka.'
            },
            {
                title: '9. Contact Information',
                content: 'Stut Instruments | info@gascart.in | www.gascart.in | Sirsi, Karnataka, India'
            }
        ];

        terms.forEach(section => {
            doc.font('Helvetica-Bold').fontSize(headerFontSize).text(section.title, 50, termsY);
            termsY += 15;
            doc.font('Helvetica').fontSize(termsFontSize).text(section.content, 50, termsY, { width: 500, align: 'justify' });
            termsY += doc.heightOfString(section.content, { width: 500 }) + 15;
        });

        doc.fontSize(8).fillColor('#888888').text(
            'This is the second page of the system-generated invoice. For the latest version of terms, please visit www.gascart.in/terms.',
            50, 740, { align: 'center', width: 500 }
        );

        doc.end();
    });
};
