import PDFDocument from 'pdfkit';

// ─── Inquiry PDF ─────────────────────────────────────────────────────────────

export interface InquiryDocumentData {
    referenceNumber: string;
    clientName: string;
    clientEmail: string;
    clientPhone?: string;
    serviceRequired: string;
    timelinePreference?: string;
    projectDescription?: string;
    internalComments?: string;
    consultantName?: string;
    consultantEmail?: string;
    status: string;
    createdAt: string;
}

const renderInquiryPage = (doc: any, data: InquiryDocumentData) => {
    // Header
    doc.fillColor('#333333').font('Helvetica-Bold').fontSize(20).text('GASCART - Professional Consultation Inquiry', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).fillColor('#666666').text(`Reference: ${data.referenceNumber}`, { align: 'right' });
    doc.text(`Date: ${new Date(data.createdAt).toLocaleDateString()}`, { align: 'right' });
    doc.moveDown();

    // Consultation Info
    doc.fontSize(14).fillColor('#1a1a2e').text('Service Details', { underline: true });
    doc.fontSize(12).fillColor('#333333').text(`Service Required: ${data.serviceRequired}`);
    if (data.timelinePreference) doc.fontSize(12).text(`Timeline: ${data.timelinePreference}`);
    doc.moveDown();

    // Client Info
    doc.fontSize(14).fillColor('#1a1a2e').text('Client Information', { underline: true });
    doc.fontSize(12).fillColor('#333333').text(`Name: ${data.clientName}`);
    doc.text(`Email: ${data.clientEmail}`);
    if (data.clientPhone) doc.text(`Phone: ${data.clientPhone}`);
    doc.moveDown();

    // Expert Info
    doc.fontSize(14).fillColor('#1a1a2e').text('Assigned Expert', { underline: true });
    if (data.consultantName) {
        doc.fontSize(12).fillColor('#333333').text(`Expert: ${data.consultantName}`);
        doc.text(`Email: ${data.consultantEmail || 'N/A'}`);
    } else {
        doc.fontSize(12).fillColor('#e67e22').text('Status: Unassigned (Admin to Assign)');
    }
    doc.moveDown();

    // Project Details
    if (data.projectDescription) {
        doc.fontSize(14).fillColor('#1a1a2e').text('Project Brief', { underline: true });
        doc.fontSize(10).fillColor('#444444').text(data.projectDescription, { align: 'justify' });
        doc.moveDown();
    }

    // Internal Notes
    if (data.internalComments) {
        doc.fontSize(14).fillColor('#2c3e50').text('Internal Admin Notes (Confidential)', { underline: true });
        doc.fontSize(10).fillColor('#444444').text(data.internalComments, { align: 'justify' });
        doc.moveDown();
    }

    // Footer
    const bottom = doc.page.height - 80;
    doc.fontSize(8).fillColor('#999999').text(
        'This is a formal consultation inquiry request generated by GASCART. Confidentiality of client information and project briefs is maintained under standard platform privacy terms.',
        50,
        bottom,
        { align: 'center', width: 500 }
    );
};

export const generateInquiryPDF = async (data: InquiryDocumentData): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        renderInquiryPage(doc, data);
        doc.end();
    });
};

export const generateBulkInquiryPDF = async (items: InquiryDocumentData[]): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        items.forEach((data, index) => {
            if (index > 0) doc.addPage();
            renderInquiryPage(doc, data);
        });

        doc.end();
    });
};


// ─── RFQ PDF ─────────────────────────────────────────────────────────────────

export interface RFQDocumentData {
    rfqId: string;
    productName: string;
    submittedFields: Record<string, any>;
    userEmail: string;
    full_name?: string;
    company_name?: string;
    createdAt: string;
}

const renderRFQPage = (doc: any, data: RFQDocumentData) => {
    // Header
    doc.fillColor('#333333').font('Helvetica-Bold').fontSize(20).text('GASCART - Technical Enquiry', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).fillColor('#666666').text(`Enquiry ID: ${data.rfqId}`, { align: 'right' });
    doc.text(`Date: ${new Date(data.createdAt).toLocaleDateString()}`, { align: 'right' });
    doc.moveDown();

    // Product Info
    doc.fontSize(14).fillColor('#1a1a2e').text('Industrial Asset Details', { underline: true });
    doc.fontSize(12).fillColor('#333333').text(`Asset Name: ${data.productName}`);
    doc.moveDown();

    // Customer Info
    doc.fontSize(14).fillColor('#1a1a2e').text('Client Information', { underline: true });
    doc.fontSize(12).fillColor('#333333').text(`Email: ${data.userEmail}`);
    if (data.full_name) doc.fontSize(12).text(`Name: ${data.full_name}`);
    if (data.company_name) doc.fontSize(12).text(`Company: ${data.company_name}`);
    doc.moveDown();

    // Technical Specifications
    doc.fontSize(14).fillColor('#1a1a2e').text('Technical Requirements', { underline: true });
    doc.moveDown(0.5);

    Object.entries(data.submittedFields).forEach(([label, value]) => {
        // Skip metadata fields if they exist
        if (['enquiry_id', 'company_name', 'item_quantity', 'item_price'].includes(label)) return;
        
        doc.fontSize(10).font('Helvetica-Bold').fillColor('#333333').text(`${label}: `, { continued: true });
        doc.font('Helvetica').fillColor('#444444').text(`${value}`);
        doc.moveDown(0.5);
    });

    // Footer
    const bottom = doc.page.height - 80;
    doc.fontSize(8).fillColor('#999999').text(
        'This is a system-generated technical requisition document. Confidentiality of engineering parameters is maintained under standard GASCART NDA terms.',
        50,
        bottom,
        { align: 'center', width: 500 }
    );
};

export const generateRFQPDF = async (data: RFQDocumentData): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        renderRFQPage(doc, data);
        doc.end();
    });
};

export const generateBulkRFQPDF = async (items: RFQDocumentData[]): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        items.forEach((data, index) => {
            if (index > 0) doc.addPage();
            renderRFQPage(doc, data);
        });

        doc.end();
    });
};

// ─── Invoice PDF ──────────────────────────────────────────────────────────────

export interface InvoiceOrderItem {
    quantity: number;
    price_at_purchase: number;
    product?: { name?: string; advance_payment_percentage?: number };
}

export interface InvoiceShippingAddress {
    full_name?: string;
    address_line1?: string;
    city?: string;
    state?: string;
    postal_code?: string;
    zip_code?: string;
    phone?: string;
}

export interface InvoiceData {
    orderId: string;
    orderOrderId?: string; // Optional support for different key names if needed
    createdAt: string;
    paymentStatus: string;
    razorpayPaymentId?: string;
    totalAmount: number;
    paidAmount?: number;
    balanceDue?: number;
    orderItems: InvoiceOrderItem[];
    shippingAddress: InvoiceShippingAddress;
    profile?: { full_name?: string; email?: string };
}

export const generateInvoicePDF = (data: InvoiceData): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        // Create document with strict bottom margin to prevent auto-breaks too early
        const doc = new PDFDocument({ 
            margin: 50,
            autoFirstPage: true
        });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        const shortId = data.orderId.slice(-8).toUpperCase();

        renderInvoice(doc, data);

        doc.end();
    });
};

export const renderInvoice = (doc: PDFKit.PDFDocument, data: InvoiceData) => {
    const shortId = data.orderId.slice(-8).toUpperCase();

    // ─── Header & Branding ────────────────────────────────────────────────
    doc.fillColor('#0f172a').font('Helvetica-Bold').fontSize(24).text('GASCART', 50, 50);
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#64748b').text('Stut Instruments', 50, 80, { characterSpacing: 1.5 });
    doc.font('Helvetica').fontSize(8).fillColor('#64748b').text('GST NO : 29AGKPH4294H1Z0', 50, 92, { characterSpacing: 1 });
        
        doc.fontSize(9).font('Helvetica').fillColor('#334155');
        doc.text('No 52, Kelagina Onikeri, Melina Onikeri Post', 50, 104);
        doc.text('Sirsi, Uttara Kannada, Karnataka - 581412', 50, 116);
        doc.text('info@gascart.in | +91 9739903856', 50, 128);

        doc.font('Helvetica-Bold').fontSize(24).fillColor('#0f172a').text('PAYMENT RECEIPT', 200, 50, { align: 'right' });
        doc.font('Helvetica-Bold').fontSize(9).fillColor('#64748b');
        doc.text(`ID: INV-${shortId}`, 200, 80, { align: 'right' });
        doc.font('Helvetica').fillColor('#334155');
        doc.text(`DATE: ${new Date(data.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).toUpperCase()}`, 200, 95, { align: 'right' });
        doc.text(`STATUS: ${data.paymentStatus.toUpperCase()}`, 200, 110, { align: 'right' });
        
        if (data.razorpayPaymentId) {
            doc.fontSize(8).text(`PAYMENT ID: ${data.razorpayPaymentId}`, 200, 125, { align: 'right' });
        }

        doc.moveTo(50, 145).lineTo(550, 145).lineWidth(1).strokeColor('#f1f5f9').stroke();

        // ─── Billing Information ──────────────────────────────────────────────
        const customerInfoTop = 165;
        doc.fontSize(10).font('Helvetica-Bold').fillColor('#64748b').text('BILL TO', 50, customerInfoTop, { characterSpacing: 1 });
        doc.fontSize(11).font('Helvetica-Bold').fillColor('#0f172a').text(data.profile?.full_name || 'Customer', 50, customerInfoTop + 18);
        doc.fontSize(9).font('Helvetica').fillColor('#475569');
        doc.text(data.profile?.email || '', 50, customerInfoTop + 33);
        if (data.shippingAddress.phone) doc.text(`Phone: ${data.shippingAddress.phone}`, 50, customerInfoTop + 46);

        doc.fontSize(10).font('Helvetica-Bold').fillColor('#64748b').text('SHIP TO', 300, customerInfoTop, { characterSpacing: 1 });
        doc.fontSize(11).font('Helvetica-Bold').fillColor('#0f172a').text(data.shippingAddress.full_name || data.profile?.full_name || 'Customer', 300, customerInfoTop + 18);
        doc.fontSize(9).font('Helvetica').fillColor('#475569');
        doc.text(data.shippingAddress.address_line1 || '', 300, customerInfoTop + 33, { width: 250 });
        doc.text(`${data.shippingAddress.city || ''}, ${data.shippingAddress.state || ''} ${data.shippingAddress.postal_code || data.shippingAddress.zip_code || ''}`, 300, doc.y + 2);

        doc.moveTo(50, 245).lineTo(550, 245).lineWidth(1).strokeColor('#f1f5f9').stroke();

        // ─── Items Table ───────────────────────────────────────────────────────
        const tableTop = 265;
        doc.fontSize(9).font('Helvetica-Bold').fillColor('#64748b').text('ITEM DESCRIPTION', 50, tableTop);
        doc.text('QTY', 320, tableTop, { width: 40, align: 'center' });
        doc.text('UNIT PRICE', 380, tableTop, { width: 80, align: 'right' });
        doc.text('TOTAL', 480, tableTop, { width: 70, align: 'right' });

        doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).lineWidth(2).strokeColor('#0f172a').stroke();

        let y = tableTop + 30;
        doc.font('Helvetica');
        
        // Safety cap on items to avoid Page 1 overflow (Strictly 2 pages requirement)
        const maxItems = 12; 
        data.orderItems.slice(0, maxItems).forEach((item: InvoiceOrderItem) => {
            const productName = item.product?.name || 'Product';
            doc.fontSize(10).fillColor('#1e293b').font('Helvetica-Bold').text(productName, 50, y, { width: 260 });
            doc.font('Helvetica').fillColor('#475569').text(item.quantity.toString(), 320, y, { width: 40, align: 'center' });
            doc.text(`INR ${item.price_at_purchase.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 380, y, { width: 80, align: 'right' });
            doc.font('Helvetica-Bold').fillColor('#0f172a').text(`INR ${(item.quantity * item.price_at_purchase).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 480, y, { width: 70, align: 'right' });
            y += 25;
            doc.moveTo(50, y - 5).lineTo(550, y - 5).lineWidth(0.5).strokeColor('#f1f5f9').stroke();
        });

        if (data.orderItems.length > maxItems) {
            doc.fontSize(8).fillColor('#ef4444').text(`+ ${data.orderItems.length - maxItems} more items (Truncated for layout consistency)`, 50, y);
            y += 15;
        }

        // ─── Summary ──────────────────────────────────────────────────────────
        y += 15;
        const summaryX = 350;
        
        const subtotal = data.totalAmount / 1.18;
        const tax = data.totalAmount - subtotal;

        doc.fontSize(10).font('Helvetica').fillColor('#64748b').text('Subtotal:', summaryX, y);
        doc.font('Helvetica-Bold').fillColor('#1e293b').text(`INR ${subtotal.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 480, y, { width: 70, align: 'right' });

        y += 20;
        doc.fontSize(10).font('Helvetica').fillColor('#64748b').text('GST (18%):', summaryX, y);
        doc.font('Helvetica-Bold').fillColor('#1e293b').text(`INR ${tax.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 480, y, { width: 70, align: 'right' });

        const paidAmount = data.paidAmount || 0;
        const balanceDue = data.balanceDue || 0;

        if (paidAmount > 0) {
            y += 20;
            doc.fontSize(10).font('Helvetica').fillColor('#64748b').text('Paid Amount:', summaryX, y);
            doc.font('Helvetica-Bold').fillColor('#1e293b').text(`INR ${paidAmount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 480, y, { width: 70, align: 'right' });
        }

        if (balanceDue > 0) {
            y += 20;
            doc.fontSize(10).font('Helvetica-Bold').fillColor('#e11d48').text('Balance Due:', summaryX, y);
            doc.text(`INR ${balanceDue.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 480, y, { width: 70, align: 'right' });
        }

        y += 30;
        doc.rect(summaryX - 10, y - 10, 210, 40).fill('#0f172a');
        doc.fillColor('#ffffff').fontSize(12).font('Helvetica-Bold').text('TOTAL AMOUNT', summaryX, y);
        doc.text(`INR ${data.totalAmount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 480, y, { width: 70, align: 'right' });

        // ─── Footer (Page 1) ──────────────────────────────────────────────────
        // Fixed absolute position to prevent auto-breaks
        const footerTop = 700;
        doc.moveTo(50, footerTop).lineTo(550, footerTop).lineWidth(1).strokeColor('#f1f5f9').stroke();
        
        doc.fontSize(8).font('Helvetica-Oblique').fillColor('#ef4444').text('* Note: If any change in applicable GST rate, the difference will be collected or refunded before final payment receipt, as the case may be.', 50, footerTop - 40, { width: 500, align: 'left' });

        doc.fontSize(8).font('Helvetica').fillColor('#94a3b8').text('THANK YOU FOR CHOOSING GASCART FOR YOUR INDUSTRIAL NEEDS.', 50, footerTop + 15, { align: 'center', characterSpacing: 1 });
        doc.text('Terms & Conditions apply (See Page 2). This is an electronically generated payment receipt.', 50, footerTop + 28, { align: 'center' });
        doc.font('Helvetica-Bold').fillColor('#0f172a').text('GASCART.IN', 50, footerTop + 42, { align: 'center', characterSpacing: 2 });

        // ─── Second Page: Terms & Conditions ──────────────────────────────────
        doc.addPage();
        
        doc.fillColor('#0f172a').font('Helvetica-Bold').fontSize(20).text('TERMS AND CONDITIONS', 50, 50, { align: 'center' });
        doc.moveTo(50, 80).lineTo(550, 80).lineWidth(2).strokeColor('#f1f5f9').stroke();
        
        let termsY = 110;
        const termsFontSize = 8;
        const headerFontSize = 10;
        
        const terms = [
            {
                title: '1. Acceptance of Terms',
                content: 'By accessing GasCart (www.gascart.in), using our services, or making a purchase, you agree to be bound by these Terms of Service. Creation of a user account or login shall constitute full acceptance.'
            },
            {
                title: '2. Nature of the Platform',
                content: 'GasCart, operated by Stut Instruments, is a B2B marketplace and sourcing facilitator for the Bio-CNG and CBG ecosystem. GasCart acts as an intermediary and is not the manufacturer or direct seller unless explicitly stated.'
            },
            {
                title: '3. Buyer Responsibilities',
                content: 'Buyers are responsible for independent technical and commercial evaluation, verifying specifications, reviewing vendor credentials, and negotiating terms directly with vendors.'
            },
            {
                title: '4. No Commercial Liability',
                content: 'GasCart is not liable for product defects, delivery delays, performance failures, or contractual disputes between buyers and vendors. Liability is limited to the facilitation fee earned by GasCart on the specific transaction.'
            },
            {
                title: '5. Payments and Transactions',
                content: 'Terms for payment, delivery, and warranty are governed by the respective vendor/OEM agreements. GasCart is not a party to the commercial contract between buyer and seller.'
            },
            {
                title: '6. Intellectual Property',
                content: 'All content and branding are owned by Stut Instruments. Users may not reproduce, copy, or exploit platform content without written permission.'
            },
            {
                title: '7. Data & Privacy',
                content: 'Use of the platform is governed by our Privacy Policy. Users consent to data sharing necessary for RFQ processing and vendor engagement.'
            },
            {
                title: '8. Governing Law',
                content: 'These terms are governed by the laws of India. Any disputes are subject to the exclusive jurisdiction of courts in Sirsi, Karnataka.'
            },
            {
                title: '9. Contact Information',
                content: 'Stut Instruments | info@gascart.in | www.gascart.in | Sirsi, Karnataka, India'
            }
        ];

        terms.forEach(section => {
            doc.font('Helvetica-Bold').fontSize(headerFontSize).fillColor('#0f172a').text(section.title, 50, termsY);
            termsY += 15;
            doc.font('Helvetica').fontSize(termsFontSize).fillColor('#475569').text(section.content, 50, termsY, { width: 500, align: 'justify' });
            termsY += doc.heightOfString(section.content, { width: 500 }) + 15;
        });

        doc.fontSize(8).fillColor('#94a3b8').text(
            'This document constitutes the entire terms of service for the associated payment receipt. For the latest digital version, visit www.gascart.in/terms.',
            50, 740, { align: 'center', width: 500 }
        );
};
